# justfile for {{crate_name}}

# Cargo build profile.
cargo_profile := "dev"
# Pocketbook SDK version. Either "5.19", "6.5", "6.8", "6.10"
pb_sdk_version := "6.10"
# Pocketbook device identifier as it's folder name when connected with USB.
# - Pocketbook Inkpad 4: "6678-3C5A"
# - Pocketbook Touch Lux 3: "PB626"
# - Pocketbook Touch 3 HD: "PB632"
pb_device := "PB632"
# Pocketbook's ssh username
pb_ssh_user := "reader"
# Pocketbook's IP address
pb_ssh_ip := "192.168.1.27"
# Pocketbook's openned port that accepts ssh connection
pb_ssh_port := "2222"
# Pocketbook's target directory, where the deployed app via SSH would land
pb_target_app_dir := "/mnt/ext1/applications"
# Pocketbook's application name your binary is going to be deployed as
pb_target_app_name := "{{crate_name}}.app"

[private]
binary := "{{crate_name}}"
[private]
ssh_key_path := "$HOME/.ssh/id_rsa"
[private]
pb_mount_root := if os() == "macos" { "/Volumes" } else { "/run/media/$USER" }
[private]
cargo_sdk_feature := "sdk-" + replace(pb_sdk_version, ".", "-")
[private]
build_target := "armv7-unknown-linux-gnueabi"
[private]
zigbuild_target := "armv7-unknown-linux-gnueabi.2.23"
[private]
cargo_out_profile := if cargo_profile == "dev" { "debug" } else { cargo_profile }

{% raw %}
default:
    just --list

[doc("""
Optional helper method.
It helps to preconfigure file descriptor limit, and to add SSH key to the ssh-agent
""")]
preconfigure-build-and-deploy-ssh:
    @echo "Setting file descriptor limit..."
    ulimit -n 4096
    @echo "Adding SSH key..."
    eval "$(ssh-agent -s)"
    ssh-add {{ ssh_key_path }}

[doc("""
build the application.
command examples:
1. `just build` -- it would take the default cargo_profile
2. `just cargo_profile=release build`
""")]
build:
    cargo zigbuild \
        --target {{ zigbuild_target }} \
        --profile {{ cargo_profile }} \
        --features={{ cargo_sdk_feature }} \
        --bin {{ binary }}
[doc("""
Transfer a built binary to the device via USB.
Command examples:
1. `just deploy-usb`
2. `just cargo_profile=release pb_device=POCKETBOOK pb_app_name="inkview-slint-demo.app" deploy-usb`
""")]
deploy-usb:
    # 1. Copying the binary to the device
    cp "target/{{ build_target / cargo_out_profile / binary }}" \
        "{{ pb_mount_root / pb_device / 'applications' / pb_target_app_name }}"
    # 2. Cleaning up macOS metadata files (if applicable)
    {{ if os() == "macos" { "dot_clean " + (pb_mount_root / pb_device / "applications") } else { "echo 'No cleanup needed'" } }}
    # 3. Flushing the filesytem cache
    sync {{ pb_mount_root / pb_device }}
    @echo "Deployment successful!"

[doc("""
Transfer a built binary to the device via SSH.
Command examples:
1. `just deploy-ssh`
2. `just cargo_profile=release deploy-ssh`
3. `just cargo_profile=release pb_user="root" pb_app_name="test.app" deploy-ssh`
""")]
deploy-ssh:
    @echo "Sending application '{{ binary }}' .."
    scp -O -P {{ pb_ssh_port }} -o HostKeyAlgorithms=+ssh-rsa \
        {{ "target" / build_target / cargo_out_profile / binary }} \
        "{{ pb_ssh_user }}@{{ pb_ssh_ip }}:'{{ pb_target_app_dir }}/{{ pb_target_app_name }}.stage'"

    @echo "Restarting application on target..."
    ssh -p {{ pb_ssh_port }} -o HostKeyAlgorithms=+ssh-rsa {{ pb_ssh_user }}@{{ pb_ssh_ip }} \
        "sh -c \"killall '{{ pb_target_app_name }}'; mv '{{ pb_target_app_dir }}/{{ pb_target_app_name }}.stage' '{{ pb_target_app_dir }}/{{ pb_target_app_name }}'; '{{ pb_target_app_dir }}/{{ pb_target_app_name }}'\""

build-deploy-ssh: build deploy-ssh

 {% endraw %}
